version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: api-service-cache
    ports:
      - "6379:6379"
    networks:
      - cache-network
    restart: unless-stopped

networks:
  cache-network:
    driver: bridge
